make_stacks: False
stack_size: 3
data_dir: ./data/lgg-mri-segmentation/kaggle_3m/
out_dir: ./data/lgg-mri-segmentation/2.5D/
model_out_pth: ./models/
augmentations: True
epochs: 20
batch_size: 8
lr: 0.0001
use_lr_scheduler: True
model: unet
model_encoder: efficientnet-b4
model_act: sigmoid
encoder_weights: imagenet
device: "cpu"
num_classes: 1

